---
name: Quiz Experts Issue
title: 'Report title'
label: ''
assignees: ''
description: Peter Griffin is busy drinking - right fix it later :p
---

Description of bug
This is a sample isue template.
